/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StocksIndexImport } from './routes/stocks/index'

// Create/Update Routes

const StocksIndexRoute = StocksIndexImport.update({
  id: '/stocks/',
  path: '/stocks/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks/': {
      id: '/stocks/'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/stocks': typeof StocksIndexRoute
}

export interface FileRoutesByTo {
  '/stocks': typeof StocksIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/stocks/': typeof StocksIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/stocks'
  fileRoutesByTo: FileRoutesByTo
  to: '/stocks'
  id: '__root__' | '/stocks/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  StocksIndexRoute: typeof StocksIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  StocksIndexRoute: StocksIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/stocks/"
      ]
    },
    "/stocks/": {
      "filePath": "stocks/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
